version: '2.4'

services:
  app:
    build:
      context: .
      target: ${TARGET:-dev}
    image: 576790146472.dkr.ecr.eu-west-1.amazonaws.com/mws_helpcenter:${TARGET:-dev}_${APP_ENV:-dev}
    command: tail -f /dev/null
    volumes:
      - ./:/workspace:cached
      - node_modules:/workspace/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mws_dev_proxy"
      - "traefik.http.routers.help_center_route.rule=Host(`help-center.mws.test`)"
    networks:
      - mws_dev_proxy
    ports:
      - 8080:8080

networks:
  mws_dev_proxy:
    external: true

volumes:
  node_modules:
